APP_PWD="Ky456lie2914dude"
OPENAI_API_KEY="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"
GEMINI_API_KEY="AIzaSyAV20yRpY1CpYNV0P3GNlPGh__0ODloCwM"
HUGGINGFACE_API_KEY="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"
GROQ_API_KEY="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"
TAVILY_API_KEY= "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"
OLLAMA_API_KEY="a2372ea2078348238b690055312728e5.zsM0T_gVy1YBjsr1T8CtE3ED"